CREATE TABLE "TICKET" (
  "ID"                NUMBER(10) NOT NULL, 
  "SCREENING_ID"      NUMBER(10) NOT NULL, 
  "CUSTOMER_ID"       NUMBER(10) NOT NULL, 
  "EMPLOYEE_ID"       NUMBER(10) NOT NULL, 
  "ROW"               VARCHAR2(1) NOT NULL, 
  "SEAT"              NUMBER(10) NOT NULL, 
  "DISCOUNT"          NUMBER(10, 2), 
  "DISCOUNT_TYPE"     VARCHAR2(255),
  "PURCHASE_DATETIME" TIMESTAMP(0) NOT NULL, 
  PRIMARY KEY ("ID"));
CREATE TABLE "MOVIE" (
  "ID"            NUMBER(10) NOT NULL, 
  "TITLE"         VARCHAR2(255) NOT NULL, 
  "DIRECTOR"      VARCHAR2(255) NOT NULL, 
  "LENGTH"        NUMBER(10), 
  "PREMIERE_DATE" DATE, 
  "GENRE"         VARCHAR2(255), 
  PRIMARY KEY ("ID"));
CREATE TABLE "ROOM" (
  "NAME"         VARCHAR2(255) NOT NULL, 
  "SEATS_IN_ROW" NUMBER(10) NOT NULL, 
  "ROWS"         NUMBER(10) NOT NULL, 
  "SPONSOR"      VARCHAR2(255), 
  "IS_3D"        NUMBER(1) NOT NULL, 
  "IS_VIP"       NUMBER(1) NOT NULL, 
  PRIMARY KEY ("NAME"));
CREATE TABLE "SCREENING" (
  "ID"               NUMBER(10) NOT NULL, 
  "ROOM_NAME"        VARCHAR2(255) NOT NULL, 
  "MOVIE_VERSION_ID" NUMBER(10) NOT NULL, 
  "DATETIME"         TIMESTAMP(0) NOT NULL, 
  "IS_PREMIERE"      NUMBER(1) NOT NULL, 
  "IS_DISCOUNTABLE"  NUMBER(1) NOT NULL, 
  "ADS_LENGTH"       NUMBER(10) NOT NULL, 
  "PRICE"            NUMBER(10, 2) NOT NULL, 
  PRIMARY KEY ("ID"));
CREATE TABLE "EMPLOYEE" (
  "ID"                 NUMBER(10) NOT NULL, 
  "NAME"               VARCHAR2(255) NOT NULL, 
  "SURNAME"            VARCHAR2(255) NOT NULL, 
  "EMAIL"              VARCHAR2(255) NOT NULL UNIQUE, 
  "PASSWORD"           VARCHAR2(255) NOT NULL, 
  "SALARY"             NUMBER(10, 2) NOT NULL, 
  "DATE_OF_EMPLOYMENT" DATE NOT NULL, 
  "SUPERVISOR_ID"      NUMBER(10), 
  PRIMARY KEY ("ID"));
CREATE TABLE "REVIEW" (
  "CUSTOMER_ID" NUMBER(10) NOT NULL, 
  "MOVIE_ID"    NUMBER(10) NOT NULL, 
  "DESCRIPTION" VARCHAR2(1000), 
  "RATING"      NUMBER(2) NOT NULL, 
  "DATE"        DATE NOT NULL, 
  "LIKES"       NUMBER(10) NOT NULL, 
  PRIMARY KEY ("CUSTOMER_ID", 
  "MOVIE_ID"));
CREATE TABLE "CUSTOMER" (
  "ID"         NUMBER(10) NOT NULL, 
  "NAME"       VARCHAR2(255) NOT NULL, 
  "SURNAME"    VARCHAR2(255) NOT NULL, 
  "EMAIL"      VARCHAR2(255) NOT NULL UNIQUE, 
  "PASSWORD"   VARCHAR2(255) NOT NULL, 
  "GENDER"     VARCHAR2(255), 
  "BIRTH_DATE" DATE, 
  PRIMARY KEY ("ID"));
CREATE TABLE "SCREENINGEMPLOYEE" (
  "SCREENING_ID"   NUMBER(10) NOT NULL, 
  "EMPLOYEE_ID"    NUMBER(10) NOT NULL, 
  "RESPONSIBILITY" VARCHAR2(255) NOT NULL, 
  PRIMARY KEY ("SCREENING_ID", 
  "EMPLOYEE_ID"));
CREATE TABLE "MOVIEVERSION" (
  "ID"            NUMBER(10) NOT NULL, 
  "MOVIE_ID"      NUMBER(10) NOT NULL, 
  "LANGUAGE"      VARCHAR2(255) NOT NULL, 
  "HAS_SUBTITLES" NUMBER(1) NOT NULL, 
  "IS_3D"         NUMBER(1) NOT NULL, 
  "IS_ATMOS"      NUMBER(1) NOT NULL, 
  PRIMARY KEY ("ID"));
ALTER TABLE "TICKET" ADD CONSTRAINT "FKTICKET757738" FOREIGN KEY ("SCREENING_ID") REFERENCES "SCREENING" ("ID") ON DELETE CASCADE;
ALTER TABLE "SCREENING" ADD CONSTRAINT "FKSCREENING419382" FOREIGN KEY ("ROOM_NAME") REFERENCES "ROOM" ("NAME") ON DELETE CASCADE;
ALTER TABLE "TICKET" ADD CONSTRAINT "FKTICKET636444" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "CUSTOMER" ("ID") ON DELETE CASCADE;
ALTER TABLE "REVIEW" ADD CONSTRAINT "FKREVIEW248108" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "CUSTOMER" ("ID") ON DELETE CASCADE;
ALTER TABLE "REVIEW" ADD CONSTRAINT "FKREVIEW173607" FOREIGN KEY ("MOVIE_ID") REFERENCES "MOVIE" ("ID") ON DELETE CASCADE;
ALTER TABLE "SCREENINGEMPLOYEE" ADD CONSTRAINT "FKSCREENINGE231457" FOREIGN KEY ("SCREENING_ID") REFERENCES "SCREENING" ("ID") ON DELETE CASCADE;
ALTER TABLE "SCREENINGEMPLOYEE" ADD CONSTRAINT "FKSCREENINGE102187" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "EMPLOYEE" ("ID") ON DELETE CASCADE;
ALTER TABLE "TICKET" ADD CONSTRAINT "FKTICKET112991" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "EMPLOYEE" ("ID") ON DELETE CASCADE;
ALTER TABLE "MOVIEVERSION" ADD CONSTRAINT "FKMOVIEVERSI830231" FOREIGN KEY ("MOVIE_ID") REFERENCES "MOVIE" ("ID") ON DELETE CASCADE;
ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "FKEMPLOYEE119678" FOREIGN KEY ("SUPERVISOR_ID") REFERENCES "EMPLOYEE" ("ID") ON DELETE CASCADE;
ALTER TABLE "SCREENING" ADD CONSTRAINT "FKSCREENING161314" FOREIGN KEY ("MOVIE_VERSION_ID") REFERENCES "MOVIEVERSION" ("ID") ON DELETE CASCADE;
