DROP TABLE Address CASCADE CONSTRAINTS;
DROP TABLE Dish CASCADE CONSTRAINTS;
DROP TABLE Employee CASCADE CONSTRAINTS;
DROP TABLE Employment CASCADE CONSTRAINTS;
DROP TABLE Ingredient CASCADE CONSTRAINTS;
DROP TABLE Restaurant_order CASCADE CONSTRAINTS;
DROP TABLE Ordered_dish CASCADE CONSTRAINTS;
DROP TABLE Product CASCADE CONSTRAINTS;
DROP TABLE Restaurant CASCADE CONSTRAINTS;
DROP TABLE Review CASCADE CONSTRAINTS;
DROP TABLE Query_execution_time CASCADE CONSTRAINTS;

