CREATE TABLE Address
(
    address_id      number(19) GENERATED BY DEFAULT AS IDENTITY,
    country         varchar2(255) NOT NULL,
    region          varchar2(255) NOT NULL,
    city            varchar2(255) NOT NULL,
    postal_code     varchar2(255) NOT NULL,
    street          varchar2(255) NOT NULL,
    building_number varchar2(255) NOT NULL,
    PRIMARY KEY (address_id)
);
CREATE TABLE Dish
(
    dish_id     number(19) GENERATED BY DEFAULT AS IDENTITY,
    price       number(6, 2)  NOT NULL,
    description varchar2(255),
    vegetarian  number        NOT NULL,
    vegan       number        NOT NULL,
    spiciness   number(1)     NOT NULL,
    name        varchar2(255) NOT NULL UNIQUE,
    category    varchar2(255) NOT NULL,
    PRIMARY KEY (dish_id)
);
CREATE TABLE Employee
(
    employee_id   number(19) GENERATED BY DEFAULT AS IDENTITY,
    address_id    number(19)    NOT NULL,
    first_name    varchar2(255) NOT NULL,
    last_name     varchar2(255) NOT NULL,
    date_of_birth date          NOT NULL,
    gender        varchar2(255) NOT NULL,
    phone_number  varchar2(255),
    PRIMARY KEY (employee_id)
);
CREATE TABLE Employment
(
    restaurant_id number(19)    NOT NULL,
    employee_id   number(19)    NOT NULL,
    salary        number(10, 2) NOT NULL,
    start_date    date          NOT NULL,
    end_date      date,
    weekly_hours  number(10)    NOT NULL,
    position      varchar2(255) NOT NULL,
    PRIMARY KEY (restaurant_id, employee_id)
);
CREATE TABLE Ingredient
(
    product_id number(19)    NOT NULL,
    dish_id    number(19)    NOT NULL,
    amount     number(19, 2) NOT NULL,
    PRIMARY KEY (product_id, dish_id)
);
CREATE TABLE Restaurant_order
(
    restaurant_order_id number(19) GENERATED BY DEFAULT AS IDENTITY,
    restaurant_id       number(19)   NOT NULL,
    waiter_id           number(19)   NOT NULL,
    table_no            number(10)   NOT NULL,
    order_time          timestamp(0) NOT NULL,
    delivery_time       timestamp(0),
    tip                 number(6, 2),
    payment_method      varchar2(255),
    remarks             varchar2(1000),
    PRIMARY KEY (restaurant_order_id)
);
CREATE TABLE Ordered_dish
(
    restaurant_order_id number(19) NOT NULL,
    dish_id             number(19) NOT NULL,
    amount              number(10) NOT NULL,
    remarks             varchar2(1000),
    PRIMARY KEY (restaurant_order_id, dish_id)
);
CREATE TABLE Product
(
    product_id         number(19) GENERATED BY DEFAULT AS IDENTITY,
    name               varchar2(255) NOT NULL UNIQUE,
    calories_per_100g  number(10),
    storing_conditions varchar2(255) NOT NULL,
    storing_unit       varchar2(255) NOT NULL,
    category           varchar2(255) NOT NULL,
    PRIMARY KEY (product_id)
);
CREATE TABLE Restaurant
(
    restaurant_id   number(19) GENERATED BY DEFAULT AS IDENTITY,
    address_id      number(19)    NOT NULL,
    seats_count     number(10)    NOT NULL,
    floor_area      number(10)    NOT NULL,
    date_of_opening date,
    name            varchar2(255) NOT NULL UNIQUE,
    PRIMARY KEY (restaurant_id)
);
CREATE TABLE Review
(
    review_id      number(19) GENERATED BY DEFAULT AS IDENTITY,
    restaurant_id  number(19)    NOT NULL,
    rating         number(1)     NOT NULL,
    review_content varchar2(1000),
    review_date    date          NOT NULL,
    reviewer_name  varchar2(255) NOT NULL,
    PRIMARY KEY (review_id)
);

ALTER TABLE Ordered_dish
    ADD CONSTRAINT FK_Ordered_Dish FOREIGN KEY (dish_id) REFERENCES Dish (dish_id) ON DELETE CASCADE;
ALTER TABLE Ordered_dish
    ADD CONSTRAINT FK_Ordered_dish_Order FOREIGN KEY (restaurant_order_id) REFERENCES Restaurant_order (restaurant_order_id) ON DELETE CASCADE;
ALTER TABLE Employment
    ADD CONSTRAINT FK_Employment_Restaurant FOREIGN KEY (restaurant_id) REFERENCES Restaurant (restaurant_id) ON DELETE CASCADE;
ALTER TABLE Employment
    ADD CONSTRAINT FK_Employment_Employee FOREIGN KEY (employee_id) REFERENCES Employee (employee_id) ON DELETE CASCADE;
ALTER TABLE Ingredient
    ADD CONSTRAINT FK_Ingredient_Product FOREIGN KEY (product_id) REFERENCES Product (product_id) ON DELETE CASCADE;
ALTER TABLE Ingredient
    ADD CONSTRAINT FK_Ingredient_Dish FOREIGN KEY (dish_id) REFERENCES Dish (dish_id) ON DELETE CASCADE;
ALTER TABLE Restaurant_order
    ADD CONSTRAINT FK_Restaurant_order_Restaurant FOREIGN KEY (restaurant_id) REFERENCES Restaurant (restaurant_id) ON DELETE CASCADE;
ALTER TABLE Restaurant
    ADD CONSTRAINT FK_Restaurant_Address FOREIGN KEY (address_id) REFERENCES Address (address_id) ON DELETE CASCADE;
ALTER TABLE Employee
    ADD CONSTRAINT FK_Employee_Address FOREIGN KEY (address_id) REFERENCES Address (address_id) ON DELETE CASCADE;
ALTER TABLE Review
    ADD CONSTRAINT FK_Review_Restaurant FOREIGN KEY (restaurant_id) REFERENCES Restaurant (restaurant_id) ON DELETE CASCADE;
ALTER TABLE Restaurant_order
    ADD CONSTRAINT FK_Restaurant_order_Employee FOREIGN KEY (waiter_id) REFERENCES Employee (employee_id) ON DELETE CASCADE;


ALTER TABLE Restaurant
    DROP CONSTRAINT FK_Restaurant_Address;
ALTER TABLE Ordered_dish
    DROP CONSTRAINT FK_Ordered_Dish;
ALTER TABLE Ordered_dish
    DROP CONSTRAINT FK_Ordered_dish_Order;
ALTER TABLE Restaurant_order
    DROP CONSTRAINT FK_Restaurant_order_Restaurant;
ALTER TABLE Restaurant_order
    DROP CONSTRAINT FK_Restaurant_order_Employee;
ALTER TABLE Employment
    DROP CONSTRAINT FK_Employment_Restaurant;
ALTER TABLE Employment
    DROP CONSTRAINT FK_Employment_Employee;
ALTER TABLE Ingredient
    DROP CONSTRAINT FK_Ingredient_Product;
ALTER TABLE Ingredient
    DROP CONSTRAINT FK_Ingredient_Dish;
ALTER TABLE Employee
    DROP CONSTRAINT FK_Employee_Address;
ALTER TABLE Review
    DROP CONSTRAINT FK_Review_Restaurant;


CREATE TABLE Query_execution_time
(
    query_execution_time_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    query_name              VARCHAR(255),
    start_time_ms           NUMBER NOT NULL,
    end_time_ms             NUMBER,
    elapsed_time_ms         NUMBER as (end_time_ms - start_time_ms),
    primary key (query_execution_time_id)
);
